import './globals.css';
import { Roboto } from 'next/font/google'
import dynamic from "next/dynamic";
const Nav = dynamic(() => import('../components/NavBar/Nav'), {
  loading: () => <p>Loading...</p>,
})
const roboto = Roboto({
  weight: '400',
  subsets: ['latin', "greek"],
})
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css'></link>
        <link
          href="https://fonts.googleapis.com/css2?family=Dancing+Script:wght@400..700&display=swap"
          rel="stylesheet"
        />
      </head>
      <body>
        <header>
          <Nav />
        </header>
        <div className={roboto.className}>
          {children}
        </div>

      </body>
    </html>
  )
}
